### ISSUE TITLE
Null value not allowed as an environment variable: RJPP_BRANCH

### ISSUE THREAD

**Issue by drubitsa** [jenkinsci/remote-file-plugin#25]
**Describe the bug**
After upgrading from version 1.13 to 1.14, job fails with following error message:
`java.lang.IllegalArgumentException: Null value not allowed as an environment variable: RJPP_BRANCH
  	at hudson.EnvVars.put(EnvVars.java:379)
  	at org.jenkinsci.plugins.workflow.multibranch.extended.RemoteJenkinsFileItemListener.buildEnvironmentFor(RemoteJenkinsFileItemListener.java:43)
  	at hudson.model.Run.getEnvironment(Run.java:2442)
  	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getEnvironment(WorkflowRun.java:492)
  	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:113)
  	at org.jenkinsci.plugins.workflow.multibranch.extended.scm.ExtendedSCMBinder.create(ExtendedSCMBinder.java:83)
  	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
  	at hudson.model.ResourceController.execute(ResourceController.java:97)
  	at hudson.model.Executor.run(Executor.java:429)`

**Screenshots**
![image](https://user-images.githubusercontent.com/33630175/108127342-6881fd00-70ab-11eb-91de-eb467ca75635.png)

**Additional context**
Configured job is a multibranch pipeline.
Jenkins version: 2.279

**Comment by Mulgikapsas** [comment]
Getting same error after plugin upgrade for any new multibranch jobs.

**Comment by leonardo-filipe** [comment]
Same here. Running Scan Organization Folder followed by Scan Multibranch Pipeline on its children pipelines seems to fix the issue for those specific pipelines. However, I had to rollback to 1.13 as I have more than 8k Multibranch Pipelines in my Jenkins instance.

I'm running Jenkins 2.263 LTS

**Comment by vvranjek** [comment]
Same here!

**Comment by aytuncbeken** [comment]
Fixed with version 1.15

**Comment by aytuncbeken** [comment]
Hey @drubitsa , @vvranjek , @Mulgikapsas , @leonardo-filipe 

Is it solved. I will be glad if I can have some feedbacks from you. Thanks in advance

**Comment by Mulgikapsas** [comment]
Hi, It is still an issue in 1.15. Had to revert back to 1.12 again.

**Comment by JP69745** [comment]
After upgrading to 1.15:
```
Started by user Duval, Juri
java.lang.IllegalArgumentException: Null value not allowed as an environment variable: RJPP_BRANCH
	at hudson.EnvVars.put(EnvVars.java:379)
	at org.jenkinsci.plugins.workflow.multibranch.extended.RemoteJenkinsFileItemListener.buildEnvironmentFor(RemoteJenkinsFileItemListener.java:43)
	at hudson.model.Run.getEnvironment(Run.java:2442)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getEnvironment(WorkflowRun.java:492)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:112)
	at org.jenkinsci.plugins.workflow.multibranch.extended.scm.ExtendedSCMBinder.create(ExtendedSCMBinder.java:83)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```

After downgrading to 1.12:
```
Started by user Duval, Juri
Checking out git https://github.com/xxxxx/branches/master/workspace@script to read ./multibranch/Jenkinsfile-JDK11
The recommended git tool is: NONE
using credential xxxxx
 > git rev-parse --resolve-git-dir /var/lib/jenkins/jobs/xxxxx/branches/master/workspace@script/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/xxxxx# timeout=10
Fetching upstream changes from https://github.com/xxxxx
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
....
```

**Comment by aytuncbeken** [comment]
@Mulgikapsas @JP69745 
Thanks for details, I will check again. 
What I understood is, after upgrading from 1.12 to 1.15 this happens.

**Comment by Mulgikapsas** [comment]
@aytuncbeken Correct

**Comment by aytuncbeken** [comment]
Thank you all for the details. Finally managed to reproduce the problem and applied a fix. However,  there is one important detail. As this variable was not defined in older versions of this plugin, It is not possible to get real value for it. Therefore, RJPP_BRANCH_ENV_NAME variable will have "N/A" value. This is just a workaround to prevent "Null Pointer exception" error.

The real fix is only possible by deleting the current job and recreating it. 

This is released with 1.17. Please let me know if it is fixed for you. 

Thanks.

**Comment by Mulgikapsas** [comment]
@aytuncbeken Everything is working now. Thanks.

**Comment by aytuncbeken** [comment]
@Mulgikapsas Happy to hear. I guess It is solved for others too. 
Closing the issue.
